### ISSUE TITLE
Low Priority - Remove GGally as a dependency

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/ggplot2.utils#87]
There appears to be a [long standing](https://github.com/ggobi/ggally/issues/292) "issue" with GGally overwriting S3 methods from ggplot2. 

```
> library(ggplot2.utils)
Loading required package: ggplot2
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
```

Whilst not a technically problem it is a distraction to users and can cause doubt when loading the package. 

I don't know how dependent this package is on GGally but if its a minor dependency I think it would be cleaner to remove it in order to avoid these spurious messages.

**Comment by danielinteractive** [comment]
Does `ggstats` have the same problem or not?
If not, we can just replace `GGally` with it since I just discovered that it in turn just imports from `ggstats` and re-exports 😆 
https://github.com/ggobi/ggally/blob/master/R/reexports.R#L41

**Comment by danielinteractive** [comment]
But wait, actually what you show is the `ggpp` part that also now overwrites something. We won't be able to avoid that part

**Comment by aphalo** [comment]
The redefintions in 'ggpp' are needed to ensure backwards compatibility with current and past versions of 'ggplot2' while remaining compatible with upcoming 'ggplot2' (>= 3.5.0). This includes implementing support for the `angle` aesthetic in variations of `geom_label()` like `geom_label_s()` to match the behaviour of `geom_label()` in upcoming 'ggplot2' (>= 3.5.0). In due time, it will be possible to depend on 'ggplot2' (>= 3.5.0) and remove these defintions. This solution was suggested by who has been programing the features in 'ggplot2', not yet released to CRAN.

**Comment by danielinteractive** [comment]
Super, thanks a lot @aphalo for this valuable information! That means we won't worry about the `ggpp` part since it will resolve itself later.

**Comment by aphalo** [comment]
It also means that 'ggpp' (0.5.5) currently in CRAN is compatible with the development version of 'ggplot2' available at GitHUb  (or at least it was when I submitted it to CRAN a couple of weeks ago) while 'ggpp' (< 0.5.5) was not.
